openapi: 3.0.3
info:
  title: Order service API
  description: This API describe our order service
servers:
  - url: http://localhost:8080
    description: Localhost server
tags:
  - name: OrderController
    description: Order APIs
paths:
  "/api/v1/orders":
    post:
      tags:
        - OrderController
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateOrderDto"
        required: true
      responses:
        '201':
          description: Created
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/OrderInfoDto"
  "/api/v1/orders/{id}":
    get:
      tags:
        - OrderController
      operationId: getOrderById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/OrderDto"
  "/api/v1/orders/filter":
    get:
      tags:
        - OrderController
      operationId: getOrdersByDateAndTotal
      parameters:
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: total
          in: query
          required: false
          schema:
            type: number
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/OrderDto"
  "/api/v1/orders/exclude":
    get:
      tags:
        - OrderController
      operationId: getOrdersWithoutProduct
      parameters:
        - name: startDate
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: good
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/OrderDto"
components:
  schemas:
    CreateOrderDetailsDto:
      type: object
      properties:
        article:
          type: integer
          format: int64
        title:
          type: string
        count:
          type: integer
          format: int32
        price:
          type: number
    CreateOrderDto:
      type: object
      properties:
        number:
          type: string
        total:
          type: number
        orderDate:
          type: string
          format: date
        recipient:
          type: string
        addressDelivery:
          type: string
        typeOfPayment:
          type: string
          enum:
            - КАРТА
            - НАЛИЧНЫЕ
        typeOfDelivery:
          type: string
          enum:
            - САМОВЫВОЗ
            - ДОСТАВКА ДО ДВЕРИ
        orderDetails:
          type: array
          items:
            "$ref": "#/components/schemas/CreateOrderDetailsDto"
    OrderInfoDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
    OrderDetailsDto:
      type: object
      properties:
        article:
          type: integer
          format: int64
        title:
          type: string
        count:
          type: integer
          format: int32
        price:
          type: number
        orderId:
          type: integer
          format: int64
    OrderDto:
      type: object
      properties:
        number:
          type: string
        total:
          type: number
        orderDate:
          type: string
          format: date
        recipient:
          type: string
        addressDelivery:
          type: string
        typeOfPayment:
          type: string
          enum:
            - КАРТА
            - НАЛИЧНЫЕ
        typeOfDelivery:
          type: string
          enum:
            - САМОВЫВОЗ
            - ДОСТАВКА ДО ДВЕРИ
        orderDetails:
          type: array
          items:
            "$ref": "#/components/schemas/OrderDetailsDto"
