openapi: 3.0.3
info:
  title: Number Generate API
  description: API для генерации номера заказа
  version: 1.0.0
servers:
  - url: http://localhost:8081/api/v1/numbers
    description: Local server
paths:
  /generate-order-number:
    post:
      summary: Генерация номера заказа
      description: Генерирует уникальный номер заказа
      operationId: generateOrderNumber
      tags:
        - Number Generation
      responses:
        "200":
          description: Успешная генерация номера заказа
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NumberGenerateDto"
        "500":
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    NumberGenerateDto:
      type: object
      description: DTO сгенерированного номера заказа
      properties:
        orderNumber:
          type: string
          description: Уникальный номер заказа
          example: "0000020250211"

    ErrorResponse:
      type: object
      description: Ошибка обработки запроса
      properties:
        status:
          type: integer
          description: HTTP-код ошибки
          example: 500
        message:
          type: string
          description: Описание ошибки
          example: "Ошибка генерации номера заказа"